{% set name = "CairoSVG" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e668f96653326780036ebb0a9ff2bb59a8443d7bcfc51a14aab77b57a8e67ad

build:
  number: 1
  noarch: python
  entry_points:
    - cairosvg = cairosvg.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - cairocffi
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

test:
  requires:
    - git
  imports:
    - cairosvg
  commands:
    - cairosvg --help
    - git clone --single-branch --branch {{ version }} https://github.com/Kozea/CairoSVG.git
    - find CairoSVG/test_non_regression/svg -maxdepth 1 -type f -name '*.svg' -exec echo {} \; -exec cairosvg -u {} -o {}.png \;
    - find CairoSVG/test_non_regression/svg -maxdepth 1 -type f -name '*.svg' -exec test -s {}.png || -exec touch a_test_failed \;
    - test ! a_test_failed
#    - cairosvg CairoSVG/test_non_regression/svg/toap04.svg -o test.png
#    - test -s test.png
#    - for %%v in (cairosvg/test_non_regression/svg/*.svg) do (echo %%v & cairosvg -u "cairosvg/test_non_regression/svg/%%v" -o "%%v.png")
#    - for %%v in (cairosvg/test_non_regression/svg/*.svg) do test -s "%%v.png"

about:
  home: http://www.cairosvg.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A Simple SVG Converter based on Cairo'
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
