{% set name = "CairoSVG" %}
{% set version = "1.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f66e0f3a2711d2e36952bb370fcd45837bfedce2f7882935c46c45c018a21557

build:
  number: 0
  noarch: python
  entry_points:
    - cairosvg = cairosvg.__init__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - pycairo
    - cairocffi
    - lxml
    - cssselect
    - tinycss

test:
  requires:
    - git
  imports:
    - cairosvg
  commands:
    - cairosvg --help
    - git clone --single-branch --branch {{ version }} https://github.com/Kozea/CairoSVG.git
    - cd CairoSVG/test # Needed for SVGs that use relative paths
    - find ./svg -maxdepth 1 -type f -name '*.svg' -exec echo {} \; -exec cairosvg -u {} -o {}.png \;
    - find ./svg -maxdepth 1 -type f -name '*.svg' -exec test ! -s {}.png \; -exec touch a_test_failed \;
    - find ./svg -maxdepth 1 -type f -name '*.svgz' -exec echo {} \; -exec cairosvg -u {} -o {}.png \;
    - find ./svg -maxdepth 1 -type f -name '*.svgz' -exec test ! -s {}.png \; -exec touch a_test_failed \;
    - test ! -e a_test_failed

about:
  home: http://www.cairosvg.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'A Simple SVG Converter based on Cairo'
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
